// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vkcxoxoxrpllcbyhdyam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZrY3hveG94cnBsbGNieWhkeWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MDQzMTYsImV4cCI6MjA3MzA4MDMxNn0.vmq9Cj9v_ejZEHey0UjjVumBsO6kj1oko9NC2kerwEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});